trigger:
  branches:
    include:
      - main

    exclude:
      - develop
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/install-dependencies.yaml




  # Run all tests
  - script: |
      TEMP_DIR=$(mktemp -d)  # Creates a temporary directory
      robot --variable BROWSER:chrome --variable OPTIONS:"--headless --disable-gpu --incognito --user-data-dir=${TEMP_DIR}" \
      --output results/logs/output_all_test.xml --log results/logs/log_all_test.html --report results/logs/report_all_test.html tests/
    displayName: 'Run All Tests'

  # Publish the Robot Framework reports as pipeline artifacts.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports-main'
    displayName: 'Publish Robot Framework Reports'


